### ISSUE TITLE
Klassifikasjoner vs kodelister

### ISSUE THREAD

**Issue by JALinnerud** [Informasjonsforvaltning/xkos-ap-no#19]
Klassifikasjoner vs kodelister "En «kodeliste» trenger dessuten ikke å være uttømmende, og kategoriene på listen trenger heller ikke å være gjensidig utelukkende. "
10. november 2021 "Fra Anne Gro: Vi sa jo lenge dette, men i det siste har jeg fjernet det. Jeg mener at dersom kategoriene er overlappende, får vi tvetydigheter – problemer med å vite i hvilke kategorier enheter skal plasseres. Og det bør vi unngå både for klassifikasjoner og kodelister"
10. november 2021 "Fra Jim: hvis kategoriene er gjensidig utelukkende, så snakker vi om klassifikasjoner og ikke kodelister, syns jeg. Poenget med teksten her er å skille mellom disse.  
Ingen endring"
16. november 2021 "Fra Anne Gro: Det jeg egentlig mente her, er at kategoriene ikke trenger å være gjensidig utelukkende, men de må ikke være overlappende. F.eks. når en har ei kodeliste for mediabruk, «Internett, Avis, TV osv.,» så er de ikke gjensidig utelukkende, noen kan drive med alle disse kategoriene samtidig, men ingen av disse kategoriene er overlappende. Hvis de er overlappende, får vi problemer med å vite hvilken kategori som skal velges, og ulike folk vil velge ulike kategorier for samme enhet."
19. mai 2022 "Fra Anne Gro: Fastholder denne kommentaren:
f.eks. hvis vi har ei tenkt kodeliste med kategoriene 
1. tenåringer
2. ungdomsskoleelever 
så ville alle plassere en 18-åring i kategori 1, mens noen ville plassere en 14-åring i kategori 1, og noen i kategori 2, fordi disse er overlappende."

**Comment by jimjyang** [comment]
Hensikten med den aktuelle teksten i spesifikasjonen er å argumentere for hvorfor ordet "klassifikasjon" blir valgt brukt for/i denne spesifikasjonen og ikke "kodeliste". 

En "kodeliste" i ordets direkte betydning er en liste over koder, og en "klassifikasjon" resultatet av å klassifisere ting. Det er derfor ingen "medførte" krav til at kodene på en kodeliste skal være gjensidig utelukkende (mens det å klassifisere ting "medfører" at kategoriene er gjensidig utelukkende selv om det finnes ikke-veldefinerte klassifikasjoner som ikke oppfyller dette kravet).

For at en ting skal kunne _entydig_ sorteres inn under én og bare én kategori, skal tingene være kategorisert og ikke samlet sammen i en liste, og da snakker vi om klassifikasjoner. 

Foreslår fremdeles ingen endring.

**Comment by JALinnerud** [comment]
Fra Anne Gro: #19 og 21: Disse er også ok siden de skal brukes i andre forbindelser enn kun statistikk. Vi gjør ting noe annerledes siden vår praktiske bruk er knyttet til statistikken. Bl.a. er alle SSBs klassifikasjoner i prinsippet vel-definerte, og våre kodelister brukes også stort sett til å klassifisere.

**Comment by jimjyang** [comment]
Flott! Da lukker jeg denne saken.
