### ISSUE TITLE
Forenklet modell med obligatoriske og anbefalte klasser samt deres obligatoriske og anbefalte egenskaper

### ISSUE THREAD

**Issue by JALinnerud** [Informasjonsforvaltning/xkos-ap-no#20]
10. november 2021 "Fra Anne Gro: Hvis klassifikasjon her er versjonen, syne jeg det er rart at gyldig fra og med kun er «recommended». Jeg ville satt den til «mandatory», den er jo helt nødvendig for å kunne bruke versjonen riktig. Gyldig til og med er jo kun mandatory når versjonen ikke lenger er gyldig, men da er den jo nødvendig."
10. november 2021 "Fra Jim: I konteksten av denne spesifikasjonen er en versjon også en klassifikasjon. 
Det fins tilfeller der man ikke klarer å oppgi gyldighet.
11. november 2021 "Fra Jim: Ingen endring"
16. november 2021 "Fra Anne Gro: Ja, vi har også hatt noen slike, men dersom dette skal brukes aktivt f.eks. i en produksjonsprosess blir det vanskelig hvis vi ikke kjenner gyldighetsperiode. For de forholdsvis få der vi ikke har kjent gyldighetsdato, har vi satt en plausibel dato passe tilbake i tid."

**Comment by jimjyang** [comment]
Anbefalt/Recommended betyr "skal oppgis _hvis_ finnes", som for versjoner vil i praksis bety at minst en av datoene skal/vil bli oppgitt. 

Foreslår derfor ingen endring.

**Comment by JALinnerud** [comment]
Fra Anne Gro: Hvis det er slik at «Anbefalt/Recommended betyr "skal oppgis hvis finnes", som for versjoner vil i praksis bety at minst en av datoene skal/vil bli oppgitt.», er det helt ok.

**Comment by jimjyang** [comment]
Jeg måtte være sikker på at min påstand om hva «anbefalt» betyr er korrekt ... 

Sjekket i DCAT-AP-NO som XKOS-AP-NO lenker til når det gjelder disse kravene, https://data.norge.no/specification/dcat-ap-no/#Om-kravene, der er det dessverre inkonsistens mellom klasse- og egenskapsnivået (slik var det i bakenforliggende EU-standarden BRegDCAT-AP også): «skal … hvis» på klassenivået og «bør … hvis» på egenskapsnivået. Denne konkrete saken gjelder en egenskap, da er det «bør ... hvis» som gjelder (inntil DCAT-AP-NO eventuelt endrer forklaringen på «anbefalt»). 

Så, hva betyr modalverbet «å burde» på folkemunne?
* [Det Norske Akademis Ordbok](https://naob.no/ordbok/burde) sier «(etter det som er rett, riktig, rimelig, tilrådelig, ønskelig) måtte ; skulle ; være forpliktet til å»
* [Bokmålsordboka](https://ordbok.uib.no/perl/ordbok.cgi?OPP=burde&ant_bokmaal=5&ant_nynorsk=5&bokmaal=+&ordbok=begge) sier noe av det samme: «(etter det som er rett, rimelig, ønskelig) måtte, skulle; ha [...] plikt til å»

Jeg mener derfor at et anefalt-krav («bør oppgi ... hvis det finnes») er ganske sterkt og forpliktende. 

Er det ok, med «anbefalt» = «bør oppgi <det> hvis <det> finnes» slik modalverbet "å burde" er definert i ordbøkene?

**Comment by JALinnerud** [comment]
Fra: Hustoft, Anne Gro 
Jeg skjønner at det blir vanskelig å gå på tvers av modellen som har «bør». Men jeg vil på det sterkeste anbefale at det fylles ut minst en gyldighetsdato, for ellers tror jeg vi kan få mange problemer i den praktiske verden- utenfor modellverdenen. Så om modellen ikke kan ta høyde for dette, bør det formidles et annet sted.

**Comment by jimjyang** [comment]
Vi kan presisere det som merknad.

**Comment by JALinnerud** [comment]
Fra Hustoft, Anne Gro
Høres greit ut.
