### ISSUE TITLE
Klassifikasjon – dekker uttømmende (xkos:coversExhaustively) 

### ISSUE THREAD

**Issue by JALinnerud** [Informasjonsforvaltning/xkos-ap-no#21]
Eksempel: Næringsgruppering dekker begrepet ‘økonomisk aktivitet’ uttømmende
19. mai 2022: "Fra Anne Gro: Jeg skjønner ikke helt hva det betyr at næringsgruppering dekker fagområdet uttømmende eller gjensidig utelukkende. I en klassifikasjon er jo alltid kategoriene uttømmende og gjensidig utelukkende derfor forstår jeg ikke helt hva som presiseres her."

**Comment by jimjyang** [comment]
En vel-definert klassifikasjon oppfyller krav til at den er uttømmende og kategoriene på hvert nivå er gjensidig utelukkende, men ikke alle klassifikasjoner. XKOS(-AP-NO) er for beskrivelse av klassifikasjoner generelt, og ikke bare de vel-definerte. I XKOS(-AP-NO) er det derfor denne muligheten til å eksplisitt si at en klassifikasjon er uttømmende og at kategoriene er gjensidig utelukkende. Næringsgruppering er brukt som eksempel i XKOS-AP-NO. 

Foreslår at vi gjør ingen endring i spesifikasjonen.

**Comment by JALinnerud** [comment]
Fra Anne Gro: #19 og 21: Disse er også ok siden de skal brukes i andre forbindelser enn kun statistikk. Vi gjør ting noe annerledes siden vår praktiske bruk er knyttet til statistikken. Bl.a. er alle SSBs klassifikasjoner i prinsippet vel-definerte, og våre kodelister brukes også stort sett til å klassifisere.

**Comment by jimjyang** [comment]
Flott! Da lukker jeg denne saken.
